#!/usr/bin/python

import os
import shutil

files={}
latest={}

for f in os.listdir('.'):
    if '-' in f:
        id, rest = f.split('-')
        vmaj,vmin = rest.split('.')[0:2] # behaves better if there's more than 2
        ver = '.'.join([vmaj,vmin])

    if files.has_key(id):
        if files[id].has_key(ver):
            files[id][ver].append(f)
        else:
            files[id][ver]=[f]
    else:
        files[id] = {ver:[f]}

    if latest.has_key(id):
        if int(latest[id][0]) < int(vmin):
            latest[id] = (vmin,ver)
    else:
        latest[id] = (vmin,ver)

todel=[]
all=[]
for f,vers in files.iteritems():
    for v,fnames in vers.iteritems():
        all.extend(fnames)
        if latest[f][1] != v:
            todel.extend(fnames)
    
#print len(todel)
for f in todel:
    # print f
    os.remove(f)
#    shutil.move(f,'/mnt/files/%s'% (f))

