#!/usr/bin/python

import os
import shutil
import sys

files = {}
latest = {}
inode2name = {}

for f in os.listdir(sys.argv[1]):
    inode = os.stat('%s/%s' % (sys.argv[1],f)).st_ino
    inode2name.setdefault(inode,[]).append(f)
    if  '@' not in f and '-' in f:
        id, rest = f.split('-')
        vmaj,vmin = rest.split('.')[0:2] # behaves better if there's more than 2
        ver = '.'.join([vmaj,vmin])

        files.setdefault(id,{}).setdefault(ver,[]).append((f,inode))

        if latest.has_key(id):
            if int(latest[id][0]) < int(vmin):
                latest[id] = (vmin,ver)
        else:
            latest[id] = (vmin,ver)

todel=[]
all=[]
for id,vers in files.iteritems():
    for v,fnames in vers.iteritems():
        all.extend(fnames)
        if latest[id][1] != v:
            todel.extend(fnames)
    
#print len(todel)
for f,i in todel:
    print '\n    '.join(inode2name[i])
#    os.remove(f)
#    shutil.move(f,'/mnt/files/%s'% (f))

