#! /bin/bash

if [ $# != 4 ]
  then echo "Usage: addldapuser username passwd givenname lastname"
else
# Expects to be called with 'username password givenname lastname' as params
newuid=`ldapsearch -x -l 0 -z 0 -b 'ou=People,dc=connexions'  uidNumber | grep '^uidNumber' |awk '$1 ~ /^uidNumber/ && $2 < 60000 && $2 > maxuid {maxuid=$2}; END {print maxuid+1}'`

if [ ${2:0:1} != '{' ]; then 
    cryptpasswd=`/usr/sbin/slappasswd -h '{CRYPT}' -c '$1$%.8s' -s $2`;
else
    cryptpasswd=$2
fi

cat user-template.ldif | sed "s/#USERNAME#/$1/"| sed "s/#UID#/$newuid/" | sed "s!#PASSWORD#!$cryptpasswd!" | sed "s/#GIVENNAME#/$3/"|sed "s/#LASTNAME#/$4/"

cat user-home-groups-template.ldif | sed "s/#USERNAME#/$1/"
fi
